### ISSUE TITLE
Update email document

### ISSUE THREAD

**Issue by kbwagner** [USAJOBS-OPM/openoppstasks#295]
- [x] Add coowners as target audience where applicable

- [x] Add new email for invite to opportunity

- [x] Sort emails - either by flow (i.e. create then apply) or by audience?

- [x] Then save on u drive U:\Open Opps\Emails - Sitewide

- [x] Join community email

by 10/15/20

**Comment by kbwagner** [comment]
Update with badge email text change

**Comment by kbwagner** [comment]
Nnamdi - can you update the document on U:\Open Opps\Emails - Sitewide with the following:

- [ ] update the badge email content from 50650 - this already exists on the document but needs to be updated
- [ ] the new emails from 53978 and the linked tickets to that once ready.  
Thanks!

**Comment by NObiako** [comment]
@kbwagner - New Co-owner email notification content has been updated in the Email Correspondence document in the D drive.

**Comment by kbwagner** [comment]
@NObiako please update again once content is finalized for 54695 thanks!

**Comment by NObiako** [comment]
@kbwagner - Email Correspondence document updated on U drive

**Comment by kbwagner** [comment]
All updates made - moving to needs review so we remember to check that any new updates are added.

**Comment by kbwagner** [comment]
@NObiako please update this document with the discussion board emails once finalized

**Comment by NObiako** [comment]
@kbwagner - Updates are complete.

**Comment by kbwagner** [comment]
@NObiako add 56839

**Comment by NObiako** [comment]
@kbwagner - This should be up to date now.

**Comment by kbwagner** [comment]
- [ ] 59196 - mentor badge email
- [ ] endorsement email

**Comment by NObiako** [comment]
@kbwagner - Email doc has been updated with 12.8 changes

**Comment by kbwagner** [comment]
- [ ] 61340 - something posted to your discussion board
- [ ] 61389 - new event posted

**Comment by kbwagner** [comment]
- [ ] 61910 - community events (community name added to email)
- [ ] 61911 - sitewide events

**Comment by kbwagner** [comment]
Two documents:

- [ ] Internship emails
- [ ] Opportunity emails
